/*
 * Uber App MVP - Registration and Login
 * An API for learning API first design approach
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UberAppMvpRegistrationAndLogin);
  }
}(this, function(expect, UberAppMvpRegistrationAndLogin) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UberAppMvpRegistrationAndLogin.CompanyApi();
  });

  describe('(package)', function() {
    describe('CompanyApi', function() {
      describe('createCompany', function() {
        it('should call createCompany successfully', function(done) {
          // TODO: uncomment, update parameter values for createCompany call
          /*
          var body = new UberAppMvpRegistrationAndLogin.Company();
          body.username = "";
          body.password = "";
          body.email = "";
          body.firstName = "";
          body.lastName = "";
          body.phone = "";
          body.status = "pending";

          instance.createCompany(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteCompany', function() {
        it('should call deleteCompany successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteCompany call
          /*
          var companyId = 789;

          instance.deleteCompany(companyId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCompanies', function() {
        it('should call getCompanies successfully', function(done) {
          // TODO: uncomment getCompanies call and complete the assertions
          /*

          instance.getCompanies(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UberAppMvpRegistrationAndLogin.Companies);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCompanyById', function() {
        it('should call getCompanyById successfully', function(done) {
          // TODO: uncomment, update parameter values for getCompanyById call and complete the assertions
          /*
          var companyId = "companyId_example";

          instance.getCompanyById(companyId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UberAppMvpRegistrationAndLogin.Company);
            expect(data.username).to.be.a('string');
            expect(data.username).to.be("");
            expect(data.password).to.be.a('string');
            expect(data.password).to.be("");
            expect(data.email).to.be.a('string');
            expect(data.email).to.be("");
            expect(data.firstName).to.be.a('string');
            expect(data.firstName).to.be("");
            expect(data.lastName).to.be.a('string');
            expect(data.lastName).to.be("");
            expect(data.phone).to.be.a('string');
            expect(data.phone).to.be("");
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("pending");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateCompany', function() {
        it('should call updateCompany successfully', function(done) {
          // TODO: uncomment, update parameter values for updateCompany call
          /*
          var body = new UberAppMvpRegistrationAndLogin.Company();
          body.username = "";
          body.password = "";
          body.email = "";
          body.firstName = "";
          body.lastName = "";
          body.phone = "";
          body.status = "pending";

          instance.updateCompany(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
