/*
 * Uber App MVP - Registration and Login
 * An API for learning API first design approach
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UberAppMvpRegistrationAndLogin);
  }
}(this, function(expect, UberAppMvpRegistrationAndLogin) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UberAppMvpRegistrationAndLogin.DriverApi();
  });

  describe('(package)', function() {
    describe('DriverApi', function() {
      describe('createDriver', function() {
        it('should call createDriver successfully', function(done) {
          // TODO: uncomment, update parameter values for createDriver call
          /*
          var body = new UberAppMvpRegistrationAndLogin.Driver();
          body.username = "";
          body.password = "";
          body.email = "";
          body.firstName = "";
          body.lastName = "";
          body.phone = "";
          body.status = "pending";

          instance.createDriver(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteDriver', function() {
        it('should call deleteDriver successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteDriver call
          /*
          var driverId = 789;

          instance.deleteDriver(driverId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDriverById', function() {
        it('should call getDriverById successfully', function(done) {
          // TODO: uncomment, update parameter values for getDriverById call and complete the assertions
          /*
          var driverId = "driverId_example";

          instance.getDriverById(driverId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UberAppMvpRegistrationAndLogin.Driver);
            expect(data.username).to.be.a('string');
            expect(data.username).to.be("");
            expect(data.password).to.be.a('string');
            expect(data.password).to.be("");
            expect(data.email).to.be.a('string');
            expect(data.email).to.be("");
            expect(data.firstName).to.be.a('string');
            expect(data.firstName).to.be("");
            expect(data.lastName).to.be.a('string');
            expect(data.lastName).to.be("");
            expect(data.phone).to.be.a('string');
            expect(data.phone).to.be("");
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("pending");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDriveraByCompanyId', function() {
        it('should call getDriveraByCompanyId successfully', function(done) {
          // TODO: uncomment, update parameter values for getDriveraByCompanyId call and complete the assertions
          /*
          var companyId = "companyId_example";

          instance.getDriveraByCompanyId(companyId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UberAppMvpRegistrationAndLogin.Drivers);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDrivers', function() {
        it('should call getDrivers successfully', function(done) {
          // TODO: uncomment getDrivers call and complete the assertions
          /*

          instance.getDrivers(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UberAppMvpRegistrationAndLogin.Drivers);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateDriver', function() {
        it('should call updateDriver successfully', function(done) {
          // TODO: uncomment, update parameter values for updateDriver call
          /*
          var body = new UberAppMvpRegistrationAndLogin.Driver();
          body.username = "";
          body.password = "";
          body.email = "";
          body.firstName = "";
          body.lastName = "";
          body.phone = "";
          body.status = "pending";

          instance.updateDriver(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
