/*
 * Uber App MVP - Registration and Login
 * An API for learning API first design approach
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Driver', 'model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Driver'), require('./User'));
  } else {
    // Browser globals (root is window)
    if (!root.UberAppMvpRegistrationAndLogin) {
      root.UberAppMvpRegistrationAndLogin = {};
    }
    root.UberAppMvpRegistrationAndLogin.Company = factory(root.UberAppMvpRegistrationAndLogin.ApiClient, root.UberAppMvpRegistrationAndLogin.Driver, root.UberAppMvpRegistrationAndLogin.User);
  }
}(this, function(ApiClient, Driver, User) {
  'use strict';

  /**
   * The Company model module.
   * @module model/Company
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Company</code>.
   * @alias module:model/Company
   * @class
   * @extends module:model/User
   */
  var exports = function() {
    User.call(this);
  };

  /**
   * Constructs a <code>Company</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Company} obj Optional instance to populate.
   * @return {module:model/Company} The populated <code>Company</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      User.constructFromObject(data, obj);
      if (data.hasOwnProperty('companyId'))
        obj.companyId = ApiClient.convertToType(data['companyId'], 'Number');
      if (data.hasOwnProperty('companyName'))
        obj.companyName = ApiClient.convertToType(data['companyName'], 'String');
      if (data.hasOwnProperty('companyAddress'))
        obj.companyAddress = ApiClient.convertToType(data['companyAddress'], 'String');
      if (data.hasOwnProperty('companyVat'))
        obj.companyVat = ApiClient.convertToType(data['companyVat'], 'String');
      if (data.hasOwnProperty('driversList'))
        obj.driversList = ApiClient.convertToType(data['driversList'], [Driver]);
    }
    return obj;
  }

  exports.prototype = Object.create(User.prototype);
  exports.prototype.constructor = exports;
  /**
   * @member {Number} companyId
   */
  exports.prototype.companyId = undefined;

  /**
   * @member {String} companyName
   */
  exports.prototype.companyName = undefined;

  /**
   * @member {String} companyAddress
   */
  exports.prototype.companyAddress = undefined;

  /**
   * @member {String} companyVat
   */
  exports.prototype.companyVat = undefined;

  /**
   * @member {Array.<module:model/Driver>} driversList
   */
  exports.prototype.driversList = undefined;

  return exports;

}));
