/*
 * Uber App MVP - Registration and Login
 * An API for learning API first design approach
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Driver', 'model/Drivers'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Driver'), require('../model/Drivers'));
  } else {
    // Browser globals (root is window)
    if (!root.UberAppMvpRegistrationAndLogin) {
      root.UberAppMvpRegistrationAndLogin = {};
    }
    root.UberAppMvpRegistrationAndLogin.DriverApi = factory(root.UberAppMvpRegistrationAndLogin.ApiClient, root.UberAppMvpRegistrationAndLogin.Driver, root.UberAppMvpRegistrationAndLogin.Drivers);
  }
}(this, function(ApiClient, Driver, Drivers) {
  'use strict';

  /**
   * Driver service.
   * @module api/DriverApi
   * @version 1.0.0
   */

  /**
   * Constructs a new DriverApi. 
   * @alias module:api/DriverApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createDriver operation.
     * @callback module:api/DriverApi~createDriverCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create driver
     * Create a new Driver
     * @param {module:model/Driver} body Driver object that need to be created.
     * @param {module:api/DriverApi~createDriverCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.createDriver = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createDriver");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/drivers', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteDriver operation.
     * @callback module:api/DriverApi~deleteDriverCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a Driver using driver ID
     * todo
     * @param {Number} driverId Driver id to delete
     * @param {module:api/DriverApi~deleteDriverCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteDriver = function(driverId, callback) {
      var postBody = null;

      // verify the required parameter 'driverId' is set
      if (driverId === undefined || driverId === null) {
        throw new Error("Missing the required parameter 'driverId' when calling deleteDriver");
      }


      var pathParams = {
        'driverId': driverId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/drivers/{driverId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getDriverById operation.
     * @callback module:api/DriverApi~getDriverByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Driver} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Driver by driverID
     * todo
     * @param {String} driverId The driverId that needs to be fetched. Use 1111 for testing. 
     * @param {module:api/DriverApi~getDriverByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Driver}
     */
    this.getDriverById = function(driverId, callback) {
      var postBody = null;

      // verify the required parameter 'driverId' is set
      if (driverId === undefined || driverId === null) {
        throw new Error("Missing the required parameter 'driverId' when calling getDriverById");
      }


      var pathParams = {
        'driverId': driverId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Driver;

      return this.apiClient.callApi(
        '/drivers/{driverId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getDriveraByCompanyId operation.
     * @callback module:api/DriverApi~getDriveraByCompanyIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Drivers} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all drivers within a Company
     * todo
     * @param {String} companyId The ID of company whoes drivers needs to be fetched. Use XXXXXX for testing. 
     * @param {module:api/DriverApi~getDriveraByCompanyIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Drivers}
     */
    this.getDriveraByCompanyId = function(companyId, callback) {
      var postBody = null;

      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getDriveraByCompanyId");
      }


      var pathParams = {
        'companyId': companyId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Drivers;

      return this.apiClient.callApi(
        '/drivers/company/{companyId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getDrivers operation.
     * @callback module:api/DriverApi~getDriversCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Drivers} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get list of drivers
     * Get list of drivers
     * @param {module:api/DriverApi~getDriversCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Drivers}
     */
    this.getDrivers = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Drivers;

      return this.apiClient.callApi(
        '/drivers', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateDriver operation.
     * @callback module:api/DriverApi~updateDriverCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update an existing Driver
     * todo
     * @param {module:model/Driver} body Driver object that needs to be added to the store
     * @param {module:api/DriverApi~updateDriverCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateDriver = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateDriver");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/drivers', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
