/*
 * Uber App MVP - Registration and Login
 * An API for learning API first design approach
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UberAppMvpRegistrationAndLogin);
  }
}(this, function(expect, UberAppMvpRegistrationAndLogin) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Company', function() {
      beforeEach(function() {
        instance = new UberAppMvpRegistrationAndLogin.Company();
      });

      it('should create an instance of Company', function() {
        // TODO: update the code to test Company
        expect(instance).to.be.a(UberAppMvpRegistrationAndLogin.Company);
      });

      it('should have the property companyId (base name: "companyId")', function() {
        // TODO: update the code to test the property companyId
        expect(instance).to.have.property('companyId');
        // expect(instance.companyId).to.be(expectedValueLiteral);
      });

      it('should have the property companyName (base name: "companyName")', function() {
        // TODO: update the code to test the property companyName
        expect(instance).to.have.property('companyName');
        // expect(instance.companyName).to.be(expectedValueLiteral);
      });

      it('should have the property companyAddress (base name: "companyAddress")', function() {
        // TODO: update the code to test the property companyAddress
        expect(instance).to.have.property('companyAddress');
        // expect(instance.companyAddress).to.be(expectedValueLiteral);
      });

      it('should have the property companyVat (base name: "companyVat")', function() {
        // TODO: update the code to test the property companyVat
        expect(instance).to.have.property('companyVat');
        // expect(instance.companyVat).to.be(expectedValueLiteral);
      });

      it('should have the property driversList (base name: "driversList")', function() {
        // TODO: update the code to test the property driversList
        expect(instance).to.have.property('driversList');
        // expect(instance.driversList).to.be(expectedValueLiteral);
      });

    });
  });

}));
